# FIFA Player Dataset: Data Cleaning and Preparation

This notebook cleans the FIFA 21 player dataset and standardises selected fields for downstream analysis. It focuses on transparent transformations, explicit missing-value handling, and portable file paths.

## 1. Project setup

 The raw dataset has been included in this repository saved as`data/fifa21_raw_data_v2.csv`; obtain it from the dataset source you are authorised to use. The notebook will stop with a clear message if the file is missing.

The cleaned output is written to `output/fifa_cleaned.csv`.

In [18]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

print("\nFiles in the current directory:")
for path in Path.cwd().iterdir():
    print(path.name)

print("\nCSV files found in subdirectories:")
for path in Path.cwd().rglob("*.csv"):
    print(path)

Current working directory:
/content/Data-Cleaning

Files in the current directory:
fifa21 raw data v2.csv
.git
output
requirements.txt
README.md
Fifa Data Cleaning.ipynb
.gitignore

CSV files found in subdirectories:
/content/Data-Cleaning/fifa21 raw data v2.csv
/content/Data-Cleaning/output/fifa_cleaned.csv

In [19]:
%cd /content

!if [ ! -d /content/Data-Cleaning/.git ]; then \
  git clone --depth 1 --branch portfolio/fifa-notebook-reproducibility \
  https://github.com/Henzo360/Data-Cleaning.git /content/Data-Cleaning; \
fi

%cd /content/Data-Cleaning

!ls -lh *.csv

/content
/content/Data-Cleaning
-rw-r--r-- 1 root root 8.1M Oct 17 06:21 'fifa21 raw data v2.csv'

In [20]:
from pathlib import Path
import re

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

DATA_CANDIDATES = [
    Path("data") / "fifa21_raw_data_v2.csv",
    Path("fifa21 raw data v2.csv"),
    Path("fifa21_raw_data_v2.csv"),
]
DATA_PATH = next((path for path in DATA_CANDIDATES if path.exists()), DATA_CANDIDATES[0])
OUTPUT_PATH = Path("output") / "fifa_cleaned.csv"

if not DATA_PATH.exists():
    expected_paths = ", ".join(str(path) for path in DATA_CANDIDATES)
    raise FileNotFoundError(
        f"Could not find the FIFA source CSV. Checked: {expected_paths}"
    )

fifa_df = pd.read_csv(DATA_PATH, low_memory=False)
print(f"Loaded {fifa_df.shape[0]:,} rows and {fifa_df.shape[1]:,} columns.")

Loaded 18,979 rows and 77 columns.

## 2. Inspect the raw data

Check the dataset's dimensions, column types, sample records, missing values, and duplicate rows before transforming it.

In [21]:
display(fifa_df.head())
print("\nDataset shape:", fifa_df.shape)
fifa_df.info()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,Right,91,CAM,"Aug 30, 2015",NaN,€129M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,Right,91,LW,"Aug 3, 2017",NaN,€132M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,595

Dataset shape: (18979, 77)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

In [22]:
missing_before = (
    fifa_df.isna()
    .sum()
    .loc[lambda counts: counts.gt(0)]
    .sort_values(ascending=False)
)
display(missing_before.to_frame("missing_count"))
print(f"Exact duplicate rows before cleaning: {fifa_df.duplicated().sum():,}")

               missing_count
Loan Date End          17966
Hits                    2595

Exact duplicate rows before cleaning: 0

## 3. Remove non-analytical columns and duplicate rows

The photo and profile URL fields are omitted because they are not needed for the tabular cleaning tasks below. Only columns that exist in the input file are dropped, so the notebook is resilient to small schema variations.

In [23]:
columns_to_drop = ["photoUrl", "playerUrl", "LongName"]
fifa_df = fifa_df.drop(columns=columns_to_drop, errors="ignore")

duplicate_count = int(fifa_df.duplicated().sum())
if duplicate_count:
    fifa_df = fifa_df.drop_duplicates().copy()
print(f"Exact duplicate rows removed: {duplicate_count:,}")

Exact duplicate rows removed: 0

## 4. Handle missing values

`Loan Date End` is retained only long enough to measure its missingness. In the original dataset it was missing for more than 94% of rows, so it is dropped from this cleaned analysis dataset. Missing `Hits` values are **not** automatically replaced with zero: a missing value does not prove that a player's page had zero visits.

In [24]:
if "Loan Date End" in fifa_df.columns:
    loan_missing_pct = fifa_df["Loan Date End"].isna().mean() * 100
    print(f"Loan Date End missing: {loan_missing_pct:.2f}%")
    fifa_df = fifa_df.drop(columns=["Loan Date End"])

Loan Date End missing: 94.66%

## 5. Standardise text and contract fields

Trim whitespace from text fields. Split the contract information into a broad contract type and an end-date field. Loan records may contain a full date, while standard contracts often contain a year; the output preserves the available representation rather than forcing both into the same date format.

In [25]:
if "Club" in fifa_df.columns:
    fifa_df["Club"] = fifa_df["Club"].astype("string").str.replace(r"\s+", " ", regex=True).str.strip()

def parse_contract_type(value):
    if pd.isna(value):
        return pd.NA
    value = str(value).strip()
    if value.lower() == "free":
        return "Free"
    if "on loan" in value.lower():
        return "Loan"
    return "Active"

def parse_contract_end(value):
    if pd.isna(value):
        return pd.NA
    value = str(value).strip()
    if value.lower() == "free":
        return pd.NA
    if "~" in value:
        return value.split("~", maxsplit=1)[1].strip()
    if " on loan" in value.lower():
        return re.split(r"\s+on loan", value, flags=re.IGNORECASE)[0].strip()
    return pd.NA

if "Contract" in fifa_df.columns:
    fifa_df["Contract_type"] = fifa_df["Contract"].map(parse_contract_type).astype("category")
    fifa_df["Contract_end"] = fifa_df["Contract"].map(parse_contract_end).astype("string")
    fifa_df = fifa_df.drop(columns=["Contract"])

## 6. Convert height and weight to standard units

Height is converted to centimetres and weight to kilograms. Unrecognised or missing values become missing values instead of causing a conversion failure.

In [26]:
def parse_height_cm(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    cm_match = re.fullmatch(r"(\d+(?:\.\d+)?)\s*cm", text)
    if cm_match:
        return float(cm_match.group(1))
    feet_match = re.fullmatch(r"(\d+)\s*'\s*(\d+)?\s*\"?", text)
    if feet_match:
        feet = int(feet_match.group(1))
        inches = int(feet_match.group(2) or 0)
        return (feet * 12 + inches) * 2.54
    return np.nan

def parse_weight_kg(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    kg_match = re.fullmatch(r"(\d+(?:\.\d+)?)\s*kg", text)
    if kg_match:
        return float(kg_match.group(1))
    lbs_match = re.fullmatch(r"(\d+(?:\.\d+)?)\s*lbs?", text)
    if lbs_match:
        return float(lbs_match.group(1)) / 2.20462
    return np.nan

if "Height" in fifa_df.columns:
    fifa_df["Height(cm)"] = fifa_df["Height"].map(parse_height_cm)
    fifa_df = fifa_df.drop(columns=["Height"])
if "Weight" in fifa_df.columns:
    fifa_df["Weight(kg)"] = fifa_df["Weight"].map(parse_weight_kg)
    fifa_df = fifa_df.drop(columns=["Weight"])

display(fifa_df[[c for c in ["Height(cm)", "Weight(kg)"] if c in fifa_df.columns]].head())

   Height(cm)  Weight(kg)
0       170.0        72.0
1       187.0        83.0
2       188.0        87.0
3       181.0        70.0
4       175.0        68.0

## 7. Convert monetary fields to numeric euros

Values with `K` and `M` suffixes are converted to their numeric equivalents. Unparseable values remain missing so they can be reviewed rather than silently coerced to zero.

In [27]:
def parse_euro_amount(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().replace("€", "").replace(",", "")
    if text in {"", "-", "—", "N/A", "n/a"}:
        return np.nan
    multiplier = 1
    if text.upper().endswith("K"):
        multiplier = 1_000
        text = text[:-1]
    elif text.upper().endswith("M"):
        multiplier = 1_000_000
        text = text[:-1]
    try:
        return float(text) * multiplier
    except ValueError:
        return np.nan

money_columns = {
    "Value": "Value(eur)",
    "Wage": "Wage(eur)",
    "Release Clause": "Release Clause(eur)",
}
for source_col, target_col in money_columns.items():
    if source_col in fifa_df.columns:
        fifa_df[target_col] = fifa_df[source_col].map(parse_euro_amount)
fifa_df = fifa_df.drop(columns=[c for c in money_columns if c in fifa_df.columns])

display(fifa_df[[c for c in money_columns.values() if c in fifa_df.columns]].head())

    Value(eur)  Wage(eur)  Release Clause(eur)
0  103500000.0   560000.0          138400000.0
1   63000000.0   220000.0           75900000.0
2  120000000.0   125000.0          159400000.0
3  129000000.0   370000.0          161000000.0
4  132000000.0   270000.0          166500000.0

## 8. Clean ratings and dates

The `W/F`, `SM`, and `IR` columns contain rating values with non-numeric symbols. Convert the numeric portion to nullable integers. Parse `Joined` as a datetime, preserving invalid or absent dates as missing. Selected descriptive fields are stored as categorical data where appropriate.

In [28]:
for column in ["W/F", "SM", "IR"]:
    if column in fifa_df.columns:
        numeric_text = fifa_df[column].astype("string").str.extract(r"(\d+(?:\.\d+)?)", expand=False)
        fifa_df[column] = pd.to_numeric(numeric_text, errors="coerce").astype("Int64")

if "Joined" in fifa_df.columns:
    fifa_df["Joined"] = pd.to_datetime(fifa_df["Joined"], errors="coerce")

for column in ["A/W", "D/W", "Preferred Foot", "Best Position"]:
    if column in fifa_df.columns:
        fifa_df[column] = fifa_df[column].astype("category")

if "Hits" in fifa_df.columns:
    hits_text = fifa_df["Hits"].astype("string").str.strip().str.upper()
    hits_numeric = pd.to_numeric(
        hits_text.str.replace(r"K$", "", regex=True), errors="coerce"
    )
    hits_numeric = hits_numeric.where(~hits_text.str.endswith("K"), hits_numeric * 1_000)
    fifa_df["Hits"] = hits_numeric.round().astype("Int64")

## 9. Validate the cleaned dataset

The checks below report remaining missing values and duplicates. Missing values are not necessarily errors: for example, an absent contract end date can be expected for free agents, and absent `Hits` values remain unknown. Review the missing-value report in the context of each column before using the dataset for analysis.

In [29]:
print("Cleaned shape:", fifa_df.shape)
print(f"Exact duplicate rows after cleaning: {fifa_df.duplicated().sum():,}")

missing_after = (
    fifa_df.isna()
    .sum()
    .loc[lambda counts: counts.gt(0)]
    .sort_values(ascending=False)
)
display(missing_after.to_frame("missing_count"))

display(fifa_df.head())
fifa_df.info()

Cleaned shape: (18979, 74)
Exact duplicate rows after cleaning: 0

              missing_count
Hits                   2595
Contract_end            237

,ID,Name,Nationality,Age,↓OVA,POT,Club,Positions,Preferred Foot,BOV,Best Position,Joined,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract_type,Contract_end,Height(cm),Weight(kg),Value(eur),Wage(eur),Release Clause(eur)
0,158023,L. Messi,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",Left,93,RW,2004-07-01,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,771,Active,2021,170.0,72.0,103500000.0,560000.0,138400000.0
1,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,"ST, LW",Right,92,ST,2018-07-10,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,562,Active,2022,187.0,83.0,63000000.0,220000.0,75900000.0
2,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,GK,Right,91,GK,2014-07-16,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,150,Active,2023,188.0,87.0,120000000.0,125000.0,159400000.0
3,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,"CAM, CM",Right,91,CAM,2015-08-30,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,207,Active,2023,181.0,70.0,129000000.0,370000.0,161000000.0
4,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",Right,91,LW,2017-08-03,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,595,Active,2022,175.0,68.0,132000000.0,270000.0,166500000.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 74 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   18979 non-null  int64
 1   Name                 18979 non-null  object
 2   Nationality          18979 non-null  object
 3   Age                  18979 non-null  int64
 4   ↓OVA                 18979 non-null  int64
 5   POT                  18979 non-null  int64
 6   Club                 18979 non-null  string
 7   Positions            18979 non-null  object
 8   Preferred Foot       18979 non-null  category
 9   BOV                  18979 non-null  int64
 10  Best Position        18979 non-null  category
 11  Joined               18979 non-null  datetime64[ns]
 12  Attacking            18979 non-null  int64
 13  Crossing             18979 non-null  int64
 14  Finishing            18979 non-null  int64
 15  Heading Accuracy     18979 non-null  int64
 16  Short Passing        18979 non-null  int64
 17  Volleys              18979 non-null  int64
 18  Skill                18979 non-null  int64
 19  Dribbling            18979 non-null  int64
 20  Curve                18979 non-null  int64
 21  FK Accuracy          18979 non-null  int64
 22  Long Passing         18979 non-null  int64
 23  Ball Control         18979 non-null  int64
 24  Movement             18979 non-null  int64
 25  Acceleration         18979 non-null  int64
 26  Sprint Speed         18979 non-null  int64
 27  Agility              18979 non-null  int64
 28  Reactions            18979 non-null  int64
 29  Balance              18979 non-null  int64
 30  Power                18979 non-null  int64
 31  Shot Power           18979 non-null  int64
 32  Jumping              18979 non-null  int64
 33  Stamina              18979 non-null  int64
 34  Strength             18979 non-null  int64
 35  Long Shots           18979 non-null  int64
 36  Mentality            18979 non-null  int64
 37  Aggression           18979 non-null  int64
 38  Interceptions        18979 non-null  int64
 39  Positioning          18979 non-null  int64
 40  Vision               18979 non-null  int64
 41  Penalties            18979 non-null  int64
 42  Composure            18979 non-null  int64
 43  Defending            18979 non-null  int64
 44  Marking              18979 non-null  int64
 45  Standing Tackle      18979 non-null  int64
 46  Sliding Tackle       18979 non-null  int64
 47  Goalkeeping          18979 non-null  int64
 48  GK Diving            18979 non-null  int64
 49  GK Handling          18979 non-null  int64
 50  GK Kicking           18979 non-null  int64
 51  GK Positioning       18979 non-null  int64
 52  GK Reflexes          18979 non-null  int64
 53  Total Stats          18979 non-null  int64
 54  Base Stats           18979 non-null  int64
 55  W/F                  18979 non-null  Int64
 56  SM                   18979 non-null  Int64
 57  A/W                  18979 non-null  category
 58  D/W                  18979 non-null  category
 59  IR                   18979 non-null  Int64
 60  PAC                  18979 non-null  int64
 61  SHO                  18979 non-null  int64
 62  PAS                  18979 non-null  int64
 63  DRI                  18979 non-null  int64
 64  DEF                  18979 non-null  int64
 65  PHY                  18979 non-null  int64
 66  Hits                 16384 non-null  Int64
 67  Contract_type        18979 non-null  category
 68  Contract_end         18742 non-null  string
 69  Height(cm)           18979 non-null  float64
 70  Weight(kg)           18979 non-null  float64
 71  Value(eur)           18979 non-null  float64
 72  Wage(eur)            18979 non-null  float64
 73  Release Clause(eur)  18979 non-null  float64
dtypes: Int64(4), category(5), datetime64[ns](1), float64(5), int64(54), object(3), string(2)
memory usage: 10.2+ MB

## 10. Export the cleaned dataset

The output folder is created automatically. The raw source data is not overwritten.

In [30]:
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
fifa_df.to_csv(OUTPUT_PATH, index=False)
print(f"Cleaned dataset saved to: {OUTPUT_PATH}")

Cleaned dataset saved to: output/fifa_cleaned.csv

In [31]:
from pathlib import Path

print("Current working directory:", Path.cwd())
print("\nCSV files found:")

for file in Path.cwd().rglob("*.csv"):
    print(file, f"({file.stat().st_size / 1024:.2f} KB)")

Current working directory: /content/Data-Cleaning

CSV files found:
/content/Data-Cleaning/fifa21 raw data v2.csv (8235.99 KB)
/content/Data-Cleaning/output/fifa_cleaned.csv (5627.33 KB)